### ISSUE TITLE
Calificacion

### ISSUE THREAD

**Issue by jmarcos-cano** [Tuki1077/Proyecto-progra-cpu#27]
Tuve que cambiar unas cosas en codigo para que corriera, solo asi no corre.

Segunda vez intentanto correr:
FileNotFoundError: [Errno 2] No such file or directory: 'machinecode.cpufm'

funciones dentro de Rom hacen print en lugar de return.

Multiples fallas que simplemente impiden calificar el proyecto; con fallas me refiero a 
que el programa nisiquiera corre al ejecutar python CU.py

Este video muestra las primeras 3 fallas de 7 que llevo hasta el momento.

[https://we.tl/t-s8JoHNpKcC](https://we.tl/t-s8JoHNpKcC)

**Comment by jmarcos-cano** [comment]
adjunto siguientes fallas 

```
File "/private/tmp/Proyecto-progra-cpu/delay.py", line 12, in Htz
    self.htz=1/self.h
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
marcoscano @ blackpearl /private/tmp/Proyecto-progra-cpu  (master *)
 └─  🐳  py CU.py 
1.2
Traceback (most recent call last):
  File "CU.py", line 5, in <module>
    from RAM import RAM
  File "/private/tmp/Proyecto-progra-cpu/RAM.py", line 6, in <module>
    from delay import delay
  File "/private/tmp/Proyecto-progra-cpu/delay.py", line 6, in <module>
    class delay:
  File "/private/tmp/Proyecto-progra-cpu/delay.py", line 8, in delay
    h = float(rom1.reloj())
TypeError: float() argument must be a string or a number, not 'NoneType'
marcoscano @ blackpearl /private/tmp/Proyecto-progra-cpu  (master *)
 └─  🐳  py CU.py 
Traceback (most recent call last):
  File "CU.py", line 11, in <module>
    class CU():
  File "CU.py", line 20, in CU
    ram1.valoress()
  File "/private/tmp/Proyecto-progra-cpu/RAM.py", line 28, in valoress
    for i in range (len(self.rom1.val)):
AttributeError: 'Rom' object has no attribute 'val'```

me es imposible calificar un proyecto asi.
